FROM python:3
WORKDIR /usr/src/app
RUN apt-get update
COPY ./requirements.txt .
COPY . ./januaryflask
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["/usr/bin/gunicorn","--config", "./januaryflask/gunicorn_config.py", "januaryflask:create_app()"]